var h={c:[{name:"Posting JQuery",url:"http://www.dte.web.id",tag:"JQuery"},{name:"Posting CSS",url:"http://www.dte.web.id",tag:"CSS"},{name:"Widget-Widget Blogger",url:"http://www.dte.web.id",tag:"Widget"}],u:4,ma:!0,la:!0,na:80,pa:"auto",oa:72,V:!1,O:"feed-list-container",U:"list-entries",$:{text:"More",P:"?max-results=20"},N:!1,current:0,X:function(){},W:function(){},r:function(a){var c=document.getElementsByTagName("head")[0],d=document.createElement("script");d.type="text/javascript";d.src=this.c[a].url+
"/feeds/posts/summary"+(this.c[a].tag?"/-/"+this.c[a].tag:"")+"?alt=json-in-script&max-results="+this.u+"&callback=listEntries";c.appendChild(d)}},k;for(k in h)h[k]=void 0!==typeof multiFeed[k]&&"undefined"!==typeof multiFeed[k]?multiFeed[k]:h[k];h.r(0);(function(a){function c(){var b;b=a(this);if(!b.data("timeago")){b.data("timeago",{a:f.a(b)});var c=a.trim(b.text());0<c.length&&b.f("title",c)}b=b.data("timeago");isNaN(b.a)||a(this).text(d(b.a));return this}function d(a){return f.q((new Date).getTime()-a.getTime())}a.b=function(b){return b instanceof Date?d(b):"string"===typeof b?d(a.b.parse(b)):d(a.b.a(b))};var f=a.b;a.extend(a.b,{d:{k:6E4,m:!1,G:{v:null,w:null,H:"yang lalu",I:"baru saja",F:"kurang dari satu menit",minute:"sekitar satu menit",
s:"%d menit",hour:"sekitar satu jam",p:"sekitar %d jam",day:"satu hari",n:"%d hari",month:"sekitar satu bulan",t:"%d bulan",year:"sekitar satu tahun",K:"%d tahun",J:" ",j:[]}},q:function(b){function c(d,f){return(a.T(d)?d(f,b):d).replace(/%d/i,e.j&&e.j[f]||f)}var e=this.d.G,d=e.v,f=e.H;this.d.m&&0>b&&(d=e.w,f=e.I);var n=Math.abs(b)/1E3,G=n/60,s=G/60,v=s/24,O=v/365,n=45>n&&c(e.F,Math.round(n))||90>n&&c(e.minute,1)||45>G&&c(e.s,Math.round(G))||90>G&&c(e.hour,1)||24>s&&c(e.p,Math.round(s))||48>s&&c(e.day,
1)||30>v&&c(e.n,Math.floor(v))||60>v&&c(e.month,1)||365>v&&c(e.t,Math.floor(v/30))||2>O&&c(e.year,1)||c(e.K,Math.floor(O));return a.trim([d,n,f].join(e.J))},parse:function(b){b=a.trim(b);b=b.replace(/\.\d\d\d+/,"");b=b.replace(/-/,"/").replace(/-/,"/");b=b.replace(/T/," ").replace(/Z/," UTC");b=b.replace(/([\+\-]\d\d)\:?(\d\d)/," $1$2");return new Date(b)},a:function(b){b="time"===a(b).get(0).tagName.toLowerCase()?a(b).f("datetime"):a(b).f("title");return f.parse(b)}});a.R.b=function(){var a=this;
a.o(c);var d=f.d;0<d.k&&setInterval(function(){a.o(c)},d.k);return a};document.createElement("abbr");document.createElement("time")})(jQuery);var aa=screen.width,la=screen.height,p=""+document.referrer;try{p=""+parent.document.referrer}catch(pa){p=""+document.referrer}var ra=0,q=0,t=-1,sa=0,u="",w="",x="",y="",z="",ta="",ua="",va="http",wa="StatCounter - Free Web Tracker and Counter",xa="",H=0,I="",ya="&u1=za",P="",R=za,za={push:function(){}};window.C&&1==window.C&&(sa=1);window.A&&(t=window.A);sc_doc_loc=""+document.location;myRE=/^https/i;sc_doc_loc.match(myRE)&&(va="https");window.ga?x=sc_local:(-1==t&&(t=1),x=va+"://c.statcounter.com/");
y=x;x=window.B?x+(window.B+"?"):window.D?x+"text.php?":x+"t.php?";window.l?("4135125"!=sc_project&&"6169619"!=sc_project&&"6222332"!=sc_project&&"5106510"!=sc_project&&"6311399"!=sc_project&&"6320092"!=sc_project&&"5291656"!=sc_project&&"7324465"!=sc_project&&"6640020"!=sc_project&&"4629288"!=sc_project&&"1480088"!=sc_project&&"2447031"!=sc_project||1==Math.floor(6*Math.random())||(q=1),x+="sc_project="+sc_project):window.qa?x+="usr="+usr:ra=1;
window.ia?ta=z="":(z='<a class="statcounter" href="http://www.statcounter.com" target="_blank">',ta="</a>");sc_date=new Date;sc_time=sc_date.getTime();sc_time_difference=36E5;u=""+document.title;w=""+document.location;p=p.substring(0,600);u=u.substring(0,300);w=w.substring(0,300);p=escape(p);u=encodeURIComponent?encodeURIComponent(u):escape(u);w=escape(w);window.ja&&(ua=sc_security);
1!=q&&("prerender"!=document.webkitVisibilityState?H=0:(H=1,document.addEventListener("webkitvisibilitychange",function(){1==H&&(H=2,Aa())},!1)));var S=parseInt(sc_project,10);
if(window.l&&(9560334==S||6709687==S||9879613==S||4124138==S||204609==S||9993602<S&&10056047>=S||10128785<S))try{(function(a,c,d,f){function b(b,f){var Ga=[];F(e(f?[b,String.fromCharCode.apply(0,a)]:0 in arguments?b:Pa(),3),Ga);var ma=new N(Ga);F(String.fromCharCode.apply(0,ma.e),a);Ha=function(){for(var a=ma.g(d),b=v,e=0;a<O;)a=(a+e)*c,b*=c,e=ma.g(1);for(;a>=Oa;)a/=2,b/=2,e>>>=1;return(a+e)/b}}function N(a){var b,e=a.length,d=this,m=0,f=d.h=d.i=0,g=d.e=[];for(e||(a=[e++]);m<c;)g[m]=m++;for(m=0;m<
c;m++)g[m]=g[f=E&f+a[m%e]+(b=g[m])],g[f]=b;(d.g=function(a){for(var b,e=0,f=d.h,g=d.i,m=d.e;a--;)b=m[f=E&f+1],e=e*c+m[E&(m[f]=m[g=E&g+b])+(m[g]=b)];d.h=f;d.i=g;return e})(c)}function e(a,b){var c=[],d=(typeof a)[0],f;if(b&&"o"==d)for(f in a)try{c.push(e(a[f],b-1))}catch(g){}return c.length?c:"s"==d?a:a+"\x00"}function F(a,b){for(var e=a+"",c,d=0;d<e.length;)b[E&d]=E&(c^=19*b[E&d])+e.charCodeAt(d++)}function Pa(){var b;try{return window.crypto.getRandomValues(b=new Uint8Array(c)),String.fromCharCode.apply(0,
b)}catch(e){return[+new Date,window,window.navigator.plugins,window.screen,String.fromCharCode.apply(0,a)]}}function n(a,b){var e=new Date;e.setTime(e.getTime()+63072E6);document.cookie="sc_is_visitor_unique="+a+"; expires="+e.toGMTString()+"; domain="+b+"; path=/"}function G(){if(document.cookie)for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var e=a[b];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf("sc_is_visitor_unique="))return e.substring(21,e.length)}return null}function s(){var a=
new Date,e=Math.round(a.getTime()/1E3)+a.getMilliseconds(),c=(navigator.userAgent||"")+(navigator.platform||""),d=[],f,g,F={Y:"application/pdf",Z:"video/quicktime",aa:"audio/x-pn-realaudio-plugin",ra:"application/x-mplayer2",dir:"application/x-director",Q:"application/x-shockwave-flash",java:"application/x-java-vm",S:"application/x-googlegears",M:"application/x-silverlight"},n=/Mac OS X.*Safari\//.test(navigator.userAgent)?window.devicePixelRatio||1:1;if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&
navigator.mimeTypes.length)for(f in F)Object.prototype.hasOwnProperty.call(F,f)&&(g=navigator.mimeTypes[F[f]],d.push(g&&g.enabledPlugin?"1":"0"));"unknown"!==typeof navigator.javaEnabled&&"undefined"!==typeof navigator.javaEnabled&&navigator.javaEnabled()&&d.push("java");"function"===typeof window.L&&d.push("gears")}d.push(screen.width*n+"x"+screen.height*n);b(c+d.join("")+a.getTimezoneOffset()+window.innerWidth+window.innerHeight+window.screen.colorDepth+document.URL+e);a="0123456789ABCDEF".split("");
e=Array(32);for(f=c=0;32>f;f++)12==f?e[f]="4":13==f?e[f]="F":(2>=c&&(c=33554432+16777216*Ha()|0),d=c&15,c>>=4,e[f]=a[19==f?d&3|8:d]);return e.join("")}var v=Math.pow(c,d),O=Math.pow(2,f),Oa=2*O,E=c-1,Ha;F(Math.random(),a);if("undefined"==typeof window.fa)var r=1;if(1==r){if("undefined"==typeof window.ca)var K=window.location.host;"."!=K.substring(0,1)&&(K="."+K);f=Math.round((new Date).getTime()/1E3);try{var U=G()}catch(ab){U=!1,I=".ex"}r="";if(U){n("",K);for(var r=U.substring(2).split("-"),V=[],
Ia=!1,g=0;g<r.length;g++){var M=r[g].split(".");if(M[0]==sc_project){var Ia=!0,J=parseInt(M[1],10);1E12<J&&(J/=1E3);"sc"==U.substring(0,2)&&(J-=1800);var na=[30,60,120,180,360,720,1440,2880,10080],Q=[];if(5>M.length)g=parseInt(M[2],10),isNaN(g)&&(g=1),Q=[g,g,g,g,g,g,g,g,g],I="."+s();else for(I="."+M[2],".0"==I&&(I="."+s()),g=0;g<na.length;g++){var oa=parseInt(M[g+3],10);isNaN(oa)&&(oa=1);Q.push(oa)}P+="&jg="+(f-J);for(g=0;g<na.length;g++)f>J+60*na[g]&&Q[g]++;P+="&rr="+Q.join(".");V.push(sc_project+
"."+f+I+"."+Q.join("."))}else V.push(r[g])}Ia||(I="."+s(),V.push(sc_project+"."+f+I+".1.1.1.1.1.1.1.1.1"),P+="&jg=new&rr=1.1.1.1.1.1.1.1.1");r=V.join("-");n("rx"+r,K)}else".ex"!=I&&(I="."+s(),r=sc_project+"."+f+I+".1.1.1.1.1.1.1.1.1",n("rx"+r,K),G()?P+="&jg=new&rr=1.1.1.1.1.1.1.1.1":I=".na");""!=I&&(ya="&u1="+I.substring(1))}})([],256,6,52)}catch(Ba){"function"!=typeof encodeURIComponent&&(encodeURIComponent=function(a){return escape(a)});var T="",T=T+("unique_returning: "+P+"\n"),T=T+("uuid: "+I+
"\n"),Ca;for(Ca in Ba)T+="property: "+Ca+" value: ["+Ba[Ca]+"]\n";T+="toString():  value: ["+Ba.toString()+"]\n";(new Image).src="http://statcounter.com/feedback/?email=javascript@statcounter.com&page_url="+encodeURIComponent(document.location.protocol+"//"+document.location.host+document.location.pathname+document.location.search+document.location.hash)+"&name=Auto%20JS&feedback_username=statcounter&pid="+sc_project+"&fake_post&user_company&feedback=consistent%20uniques%20js%20exception:%20"+encodeURIComponent(T);
P="";ya="&u1=f2"}var Da="";
(function(){function a(a,b){var c=a.__proto__||a.constructor.prototype;return b in a&&(!(b in c)||c[b]!==a[b])}function c(a){var b;b=(((b||"")+"").toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join("");return a.replace(/\x3c!--[\s\S]*?--\x3e|<\?(?:php)?[\s\S]*?\?>/gi,"").replace(/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,function(a,e){return-1<b.indexOf("<"+e.toLowerCase()+">")?a:""})}function d(a){var b=[];if(0!=a.length%2)b.push("Every tag must have a name and value.");else{5<a.length/2&&b.push("No more than 5 tags can be passed - "+
a.length/2+" passed.");for(k=0;k<a.length;k++){var d=(""+a[k]).length;(1>d||30<d)&&b.push("Tag names and values must be between 1 and 30 characters in length ('"+a[k]+"' is "+a[k].length+" characters long).")}for(k=0;k<a.length;k++)c(""+a[k])!=""+a[k]&&b.push("Tag names and values may not contain HTML tags.")}if(0!=b.length){for(k=0;k<b.length;k++)console.log("StatCounter Custom Tag Error: "+b[k]+" Tags will not be recorded for this pageview.");return!1}return!0}function f(a){for(k=0;k<a.length;k++)a[k]=
(""+a[k]).trim();return a}Object.prototype.hasOwnProperty&&(a=function(a,b){return a.hasOwnProperty(b)});if("[object Array]"===Object.prototype.toString.call(R)&&1<=R.length&&a(R[0],"tags")){var b=[],N;for(N in R[0].tags)b[b.length]=N,b[b.length]=R[0].tags[N];if(d(b))for(b=f(b),k=0;k<b.length;k+=2)Da+="&sc_ev_"+encodeURIComponent(b[k])+"="+encodeURIComponent(b[k+1])}})([],256,6,52);if(Ea)Ea++;else var Ea=1;
var Fa=x+P+ya+"&resolution="+aa+"&h="+la+"&camefrom="+p+"&u="+w+"&t="+u+"&java=1&security="+ua+"&sc_random="+Math.random()+"&sc_snum="+Ea+Da;window.ea&&window.da&&(xa=' width="'+sc_counter_width+'" height="'+sc_counter_height+'"');window.ha&&(wa="");var Ja='<span class="statcounter">'+z+'<img src="'+Fa+"&p="+H+('" alt="'+wa+'" border="0"'+xa+">")+ta+"</span>";1==ra?document.writeln("Code corrupted. Insert fresh copy."):1!=q&&Aa();
function Aa(){1==sa||2==H?(window.ba?sc_call++:sc_call=1,eval("var sc_img"+sc_call+" = new Image();sc_img"+sc_call+'.src = "'+Fa+"&p="+H+'&invisible=1"')):window.D?document.writeln('<script language="JavaScript" src='+Fa+"&p="+H+"&text="+sc_text+">\x3c/script>"):document.writeln(Ja)}
if(0<t&&1!=Ka){var Ma=function(){ad=document.getElementsByTagName("iframe");if("undefined"!=typeof W)for(var a=0;a<ad.length;a++){var c;c=ad[a];for(var d=0;c;)d+=c.offsetLeft,c=c.offsetParent;c=d;for(var d=ad[a],f=0;d;)f+=d.offsetTop,d=d.offsetParent;var d=f,b=parseInt(c,10)+parseInt(ad[a].width,10)+15,f=parseInt(d,10)+parseInt(ad[a].height,10)+10;c=W>c-10&&W<b;X>d-10&&X<f&&c&&(ad[a].src.match("googlesyndication.com|ypn-js.overture.com|ypn-js.ysm.yahoo.com|googleads.g.doubleclick.net")||ad[a].id.match("^aswift_[0-9]+$"))&&
La(ad[a])}},Na=function(a){"number"==typeof a.pageX?(W=a.pageX,X=a.pageY):"number"==typeof a.clientX&&(W=a.clientX,X=a.clientY,document.body&&(document.body.scrollLeft||document.body.scrollTop)?(W+=document.body.scrollLeft,X+=document.body.scrollTop):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&(W+=document.documentElement.scrollLeft,X+=document.documentElement.scrollTop))},Y=function(){if(document.all&&"undefined"==typeof window.opera)for(var a=
document.getElementsByTagName("iframe"),c=0;c<a.length;c++){if(a[c].src.match("googlesyndication.com|ypn-js.overture.com|ypn-js.ysm.yahoo.com|googleads.g.doubleclick.net")||a[c].id.match("^aswift_[0-9]+$"))a[c].onfocus=function(){La(this)}}else"undefined"!=typeof window.addEventListener&&(window.addEventListener("unload",Ma,!1),window.addEventListener("mousemove",Na,!0))},La=function(a){a=a.src.match("googlesyndication.com|ypn-js.overture.com|ypn-js.ysm.yahoo.com|googleads.g.doubleclick.net")?escape(a.src):
escape("Google Adsense "+a.width+"x"+a.height);(new Image).src=y+"click.gif?sc_project="+Qa+"&security="+Ra+"&c="+a+"&m=2&u="+w+"&t="+u+"&rand="+Math.random()},Ka=1,Qa=window.l,Ra=window.ka,Sa=location.host.replace(/^www\./i,"").split(".");Sa.pop();var Ta=Sa.pop();/^(ac|co|gov|ltd|me|mod|net|nic|nhs|org|plc|police|sch|com)$/i.test(Ta)&&(Ta=Sa.pop());if(document.getElementsByTagName){var Ua=document.getElementsByTagName("a");for(k=0;k<Ua.length;k++){var Z=Ua[k];if(Z.onmousedown){for(var Va=Z.onmousedown.toString().split("\n").join(" "),
Wa=Va.substr(0,Va.indexOf("{")),Xa=Wa.substring(Wa.indexOf("(")+1,Wa.indexOf(")")).split(","),$="",Ya="",Za=0;Za<Xa.length;Za++)$=Ya+"'"+Xa[Za]+"'",Ya=",";","==Ya&&($+=",");Z.onmousedown=eval("new Function ("+$+"final_body);")}else Z.onmousedown=new Function("event","sc_clickstat_call(this,'"+y+"');return true;")}}var W,X;if("undefined"!=typeof window.addEventListener)window.addEventListener("load",Y,!1);else if("undefined"!=typeof document.addEventListener)document.addEventListener("load",Y,!1);
else if("undefined"!=typeof window.attachEvent)window.attachEvent("onload",Y);else if("function"==typeof window.onload){var $a=onload;window.onload=function(){$a();Y()}}else window.onload=Y};