var mf_defaults={feedsUri:[{name:"Posting JQuery",url:"http://www.dte.web.id",tag:"JQuery"},{name:"Posting CSS",url:"http://www.dte.web.id",tag:"CSS"},{name:"Widget-Widget Blogger",url:"http://www.dte.web.id",tag:"Widget"}],numPost:4,showThumbnail:!0,showSummary:!0,summaryLength:80,titleLength:"auto",thumbSize:72,newTabLink:!1,containerId:"feed-list-container",listClass:"list-entries",readMore:{text:"More",endParam:"?max-results=20"},autoHeight:!1,current:0,onLoadFeed:function(a){},onLoadComplete:function(){},
loadFeed:function(a){var b=document.getElementsByTagName("head")[0];document.getElementById(this.containerId);var d=document.createElement("script");d.type="text/javascript";d.src=this.feedsUri[a].url+"/feeds/posts/summary"+(this.feedsUri[a].tag?"/-/"+this.feedsUri[a].tag:"")+"?alt=json-in-script&max-results="+this.numPost+"&callback=listEntries";b.appendChild(d)}},i;for(i in mf_defaults)mf_defaults[i]=void 0!==typeof multiFeed[i]&&"undefined"!==typeof multiFeed[i]?multiFeed[i]:mf_defaults[i];
function listEntries(a){a=a.feed.entry;for(var b=mf_defaults,d=document.getElementById(b.containerId),h=document.createElement("div"),c="<ul>",r=b.feedsUri.length,m,v,l,g,e=0;e<b.numPost&&e!=a.length;e++){m="auto"!==b.titleLength?a[e].title.$t.substring(0,b.titleLength)+(b.titleLength<a[e].title.$t.length?"&hellip;":""):a[e].title.$t;l="summary"in a[e]?a[e].summary.$t.replace(/<br ?\/?>/g," ").replace(/<.*?>/g,"").replace(/[<>]/g,""):"";l=b.summaryLength<l.length?l.substring(0,b.summaryLength)+"&hellip;":
l;g="media$thumbnail"in a[e]?'<img src="'+a[e].media$thumbnail.url.replace(/\/s72(\-c)?\//,"/s"+b.thumbSize+"-c/")+'" style="width:'+b.thumbSize+"px;height:"+b.thumbSize+'px;">':'<span class="fake-img" style="width:'+b.thumbSize+"px;height:"+b.thumbSize+'px;"></span>';for(var k=0,q=a[e].link.length;k<q;k++)v="alternate"==a[e].link[k].rel?a[e].link[k].href:"#";c+='<li><div class="inner"'+(b.autoHeight?"":' style="height:'+b.thumbSize+'px;overflow:hidden;"')+">";c+=b.showThumbnail?g:"";c+='<div class="title"><a href="'+
v+'"'+(b.newTabLink?' target="_blank"':"")+">"+m+"</a></div>";c+='<div class="summary">';c+="<span"+(b.showSummary?"":' style="display:none;"')+">";c+=b.showSummary?l:"";c+="</span></div>";c+='<span style="display:block;clear:both;"></span></div></li>'}c=c+"</ul>"+('<div class="more-link"><a href="'+b.feedsUri[b.current].url.replace(/\/$/,"")+"/search/label/"+b.feedsUri[b.current].tag+b.readMore.endParam+'"'+(b.newTabLink?' target="_blank"':"")+">"+b.readMore.text+"</a></div>");h.className=b.listClass;
h.innerHTML='<div class="main-title"><h4>'+b.feedsUri[b.current].name+"</h4></div>"+c;d.appendChild(h);b.onLoadFeed(b.current);b.current+1<r&&b.loadFeed(b.current+1);if(b.current+1==r)b.onLoadComplete();b.current++}mf_defaults.loadFeed(0);(function(a){function b(){var b;b=a(this);if(!b.data("timeago")){b.data("timeago",{datetime:c.datetime(b)});var m=a.trim(b.text());0<m.length&&b.attr("title",m)}b=b.data("timeago");isNaN(b.datetime)||a(this).text(d(b.datetime));return this}function d(a){return c.inWords(h(a))}function h(a){return(new Date).getTime()-a.getTime()}a.timeago=function(b){return b instanceof Date?d(b):"string"===typeof b?d(a.timeago.parse(b)):d(a.timeago.datetime(b))};var c=a.timeago;a.extend(a.timeago,{settings:{refreshMillis:6E4,
allowFuture:!1,strings:{prefixAgo:null,prefixFromNow:null,suffixAgo:"yang lalu",suffixFromNow:"baru saja",seconds:"kurang dari satu menit",minute:"sekitar satu menit",minutes:"%d menit",hour:"sekitar satu jam",hours:"sekitar %d jam",day:"satu hari",days:"%d hari",month:"sekitar satu bulan",months:"%d bulan",year:"sekitar satu tahun",years:"%d tahun",wordSeparator:" ",numbers:[]}},inWords:function(b){function c(e,g){return(a.isFunction(e)?e(g,b):e).replace(/%d/i,d.numbers&&d.numbers[g]||g)}var d=this.settings.strings,
h=d.prefixAgo,g=d.suffixAgo;this.settings.allowFuture&&0>b&&(h=d.prefixFromNow,g=d.suffixFromNow);var e=Math.abs(b)/1E3,k=e/60,q=k/60,p=q/24,A=p/365,e=45>e&&c(d.seconds,Math.round(e))||90>e&&c(d.minute,1)||45>k&&c(d.minutes,Math.round(k))||90>k&&c(d.hour,1)||24>q&&c(d.hours,Math.round(q))||48>q&&c(d.day,1)||30>p&&c(d.days,Math.floor(p))||60>p&&c(d.month,1)||365>p&&c(d.months,Math.floor(p/30))||2>A&&c(d.year,1)||c(d.years,Math.floor(A));return a.trim([h,e,g].join(d.wordSeparator))},parse:function(b){b=
a.trim(b);b=b.replace(/\.\d\d\d+/,"");b=b.replace(/-/,"/").replace(/-/,"/");b=b.replace(/T/," ").replace(/Z/," UTC");b=b.replace(/([\+\-]\d\d)\:?(\d\d)/," $1$2");return new Date(b)},datetime:function(b){b="time"===a(b).get(0).tagName.toLowerCase()?a(b).attr("datetime"):a(b).attr("title");return c.parse(b)}});a.fn.timeago=function(){var a=this;a.each(b);var d=c.settings;0<d.refreshMillis&&setInterval(function(){a.each(b)},d.refreshMillis);return a};document.createElement("abbr");document.createElement("time")})(jQuery);var sc_width=screen.width,sc_height=screen.height,sc_referer=""+document.referrer;try{sc_referer=""+parent.document.referrer}catch(ex){sc_referer=""+document.referrer}
var sc_unique=0,sc_returning=0,sc_returns=0,sc_error=0,sc_remove=0,sc_cls=-1,sc_inv=0,sc_os="",sc_title="",sc_url="",sc_base_dir="",sc_click_dir="",sc_link_back_start="",sc_link_back_end="",sc_security_code="",sc_http_url="http",sc_host="statcounter.com",sc_dc="c",sc_alt_text="StatCounter - Free Web Tracker and Counter",sc_counter_size="",sc_prerendering=0,sc_uuid="",sc_uuid_q="&u1=za",sc_unique_returning="",_statcounter_pending=_statcounter,_statcounter={push:function(a){}};
window.sc_invisible&&1==window.sc_invisible&&(sc_inv=1);window.sc_click_stat&&(sc_cls=window.sc_click_stat);sc_doc_loc=""+document.location;myRE=/^https/i;sc_doc_loc.match(myRE)&&(sc_http_url="https");window.sc_local?sc_base_dir=sc_local:(-1==sc_cls&&(sc_cls=1),sc_base_dir=sc_http_url+"://"+sc_dc+"."+sc_host+"/");sc_click_dir=sc_base_dir;sc_base_dir=window.sc_counter_target?sc_base_dir+(window.sc_counter_target+"?"):window.sc_text?sc_base_dir+"text.php?":sc_base_dir+"t.php?";
window.sc_project?("4135125"!=sc_project&&"6169619"!=sc_project&&"6222332"!=sc_project&&"5106510"!=sc_project&&"6311399"!=sc_project&&"6320092"!=sc_project&&"5291656"!=sc_project&&"7324465"!=sc_project&&"6640020"!=sc_project&&"4629288"!=sc_project&&"1480088"!=sc_project&&"2447031"!=sc_project||1==Math.floor(6*Math.random())||(sc_remove=1),sc_base_dir+="sc_project="+sc_project):window.usr?sc_base_dir+="usr="+usr:sc_error=1;
window.sc_remove_link?sc_link_back_end=sc_link_back_start="":(sc_link_back_start='<a class="statcounter" href="http://www.'+sc_host+'" target="_blank">',sc_link_back_end="</a>");sc_date=new Date;sc_time=sc_date.getTime();sc_time_difference=36E5;sc_title=""+document.title;sc_url=""+document.location;sc_referer=sc_referer.substring(0,600);sc_title=sc_title.substring(0,300);sc_url=sc_url.substring(0,300);sc_referer=escape(sc_referer);sc_title=encodeURIComponent?encodeURIComponent(sc_title):escape(sc_title);
sc_url=escape(sc_url);window.sc_security&&(sc_security_code=sc_security);1!=sc_remove&&("prerender"!=document.webkitVisibilityState?sc_prerendering=0:(sc_prerendering=1,document.addEventListener("webkitvisibilitychange",function(a){1==sc_prerendering&&(sc_prerendering=2,sc_write_data())},!1)));var _sc_project_int=parseInt(sc_project,10);
if(window.sc_project&&(9560334==_sc_project_int||6709687==_sc_project_int||9879613==_sc_project_int||4124138==_sc_project_int||204609==_sc_project_int||9993602<_sc_project_int&&10056047>=_sc_project_int||10128785<_sc_project_int))try{(function(a,b,d,h){function c(a){var d,e=a.length,c=this,g=0,h=c.i=c.j=0,f=c.S=[];for(e||(a=[e++]);g<b;)f[g]=g++;for(g=0;g<b;g++)f[g]=f[h=t&h+a[g%e]+(d=f[g])],f[h]=d;(c.g=function(a){for(var d,e=0,g=c.i,f=c.j,y=c.S;a--;)d=y[g=t&g+1],e=e*b+y[t&(y[g]=y[f=t&f+d])+(y[f]=
d)];c.i=g;c.j=f;return e})(b)}function r(a,b){var d=[],e=(typeof a)[0],c;if(b&&"o"==e)for(c in a)try{d.push(r(a[c],b-1))}catch(g){}return d.length?d:"s"==e?a:a+"\x00"}function m(a,b){for(var d=a+"",e,c=0;c<d.length;)b[t&c]=t&(e^=19*b[t&c])+d.charCodeAt(c++);return l(b)}function v(d){try{return window.crypto.getRandomValues(d=new Uint8Array(b)),l(d)}catch(c){return[+new Date,window,window.navigator.plugins,window.screen,l(a)]}}function l(a){return String.fromCharCode.apply(0,a)}function g(a,b,d){var c=
new Date;c.setTime(c.getTime()+63072E6);document.cookie=a+"="+b+"; expires="+c.toGMTString()+"; domain="+d+"; path=/"}function e(a){a+="=";if(document.cookie)for(var b=document.cookie.split(";"),d=0;d<b.length;d++){for(var c=b[d];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return null}function k(){var a=new Date,b=Math.round(a.getTime()/1E3)+a.getMilliseconds(),c=(navigator.userAgent||"")+(navigator.platform||""),d;d=[];var e,g,f={pdf:"application/pdf",
qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},h=/Mac OS X.*Safari\//.test(navigator.userAgent)?window.devicePixelRatio||1:1;if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(g=navigator.mimeTypes[f[e]],d.push(g&&
g.enabledPlugin?"1":"0"));"unknown"!==typeof navigator.javaEnabled&&"undefined"!==typeof navigator.javaEnabled&&navigator.javaEnabled()&&d.push("java");"function"===typeof window.GearsFactory&&d.push("gears")}d.push(screen.width*h+"x"+screen.height*h);d=d.join("");a=c+d+a.getTimezoneOffset()+window.innerWidth+window.innerHeight+window.screen.colorDepth+document.URL+b;H(a);a="0123456789ABCDEF".split("");b=Array(32);for(e=c=0;32>e;e++)12==e?b[e]="4":13==e?b[e]="F":(2>=c&&(c=33554432+16777216*F()|0),
d=c&15,c>>=4,b[e]=a[19==e?d&3|8:d]);return b.join("")}var q=Math.pow(b,d),p=Math.pow(2,h),A=2*p,t=b-1,F,H=function(e,g){var f=[],h=m(r(g?[e,l(a)]:0 in arguments?e:v(),3),f),k=new c(f);m(l(k.S),a);F=function(){for(var a=k.g(d),c=q,e=0;a<p;)a=(a+e)*b,c*=b,e=k.g(1);for(;a>=A;)a/=2,c/=2,e>>>=1;return(a+e)/c};return h};m(Math.random(),a);if("undefined"==typeof window.sc_first_party_cookie)var n=1;if(1==n){if("undefined"==typeof window.sc_cookie_domain)var w=window.location.host;"."!=w.substring(0,1)&&
(w="."+w);h=Math.round((new Date).getTime()/1E3);try{var B=e("sc_is_visitor_unique")}catch(I){B=!1,sc_uuid=".ex"}n="";if(B){g("sc_is_visitor_unique","",w);for(var n=B.substring(2).split("-"),C=[],G=!1,f=0;f<n.length;f++){var x=n[f].split(".");if(x[0]==sc_project){var G=!0,u=parseInt(x[1],10);1E12<u&&(u/=1E3);"sc"==B.substring(0,2)&&(u-=1800);var D=[30,60,120,180,360,720,1440,2880,10080],z=[];if(5>x.length)f=parseInt(x[2],10),isNaN(f)&&(f=1),z=[f,f,f,f,f,f,f,f,f],sc_uuid="."+k();else for(sc_uuid="."+
x[2],".0"==sc_uuid&&(sc_uuid="."+k()),f=0;f<D.length;f++){var E=parseInt(x[f+3],10);isNaN(E)&&(E=1);z.push(E)}sc_unique_returning+="&jg="+(h-u);for(f=0;f<D.length;f++)h>u+60*D[f]&&z[f]++;sc_unique_returning+="&rr="+z.join(".");C.push(sc_project+"."+h+sc_uuid+"."+z.join("."))}else C.push(n[f])}G||(sc_uuid="."+k(),C.push(sc_project+"."+h+sc_uuid+".1.1.1.1.1.1.1.1.1"),sc_unique_returning+="&jg=new&rr=1.1.1.1.1.1.1.1.1");n=C.join("-");g("sc_is_visitor_unique","rx"+n,w)}else".ex"!=sc_uuid&&(sc_uuid="."+
k(),n=sc_project+"."+h+sc_uuid+".1.1.1.1.1.1.1.1.1",g("sc_is_visitor_unique","rx"+n,w),e("sc_is_visitor_unique")?sc_unique_returning+="&jg=new&rr=1.1.1.1.1.1.1.1.1":sc_uuid=".na");""!=sc_uuid&&(sc_uuid_q="&u1="+sc_uuid.substring(1))}})([],256,6,52)}catch(e$$12){"function"!=typeof encodeURIComponent&&(encodeURIComponent=function(a){return escape(a)});var vDebug="",vDebug=vDebug+("unique_returning: "+sc_unique_returning+"\n"),vDebug=vDebug+("uuid: "+sc_uuid+"\n"),prop;for(prop in e$$12)vDebug+="property: "+
prop+" value: ["+e$$12[prop]+"]\n";var vDebug=vDebug+("toString():  value: ["+e$$12.toString()+"]\n"),sc_debug_img=new Image;sc_debug_img.src="http://statcounter.com/feedback/?email=javascript@statcounter.com&page_url="+encodeURIComponent(document.location.protocol+"//"+document.location.host+document.location.pathname+document.location.search+document.location.hash)+"&name=Auto%20JS&feedback_username=statcounter&pid="+sc_project+"&fake_post&user_company&feedback=consistent%20uniques%20js%20exception:%20"+
encodeURIComponent(vDebug);sc_unique_returning="";sc_uuid_q="&u1=f2"}var sc_pageview_tag_string="";
(function(a,b,d,h){function c(a,b){var c=a.__proto__||a.constructor.prototype;return b in a&&(!(b in c)||c[b]!==a[b])}function r(a,b){b=(((b||"")+"").toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join("");return a.replace(/\x3c!--[\s\S]*?--\x3e|<\?(?:php)?[\s\S]*?\?>/gi,"").replace(/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,function(a,c){return-1<b.indexOf("<"+c.toLowerCase()+">")?a:""})}function m(a){var b=[];if(0!=a.length%2)b.push("Every tag must have a name and value.");else{5<a.length/2&&b.push("No more than 5 tags can be passed - "+
a.length/2+" passed.");for(i=0;i<a.length;i++){var c=(""+a[i]).length;(1>c||30<c)&&b.push("Tag names and values must be between 1 and 30 characters in length ('"+a[i]+"' is "+a[i].length+" characters long).")}for(i=0;i<a.length;i++)r(""+a[i])!=""+a[i]&&b.push("Tag names and values may not contain HTML tags.")}if(0!=b.length){for(i=0;i<b.length;i++)console.log("StatCounter Custom Tag Error: "+b[i]+" Tags will not be recorded for this pageview.");return!1}return!0}function v(a){for(i=0;i<a.length;i++)a[i]=
(""+a[i]).trim();return a}Object.prototype.hasOwnProperty&&(c=function(a,b){return a.hasOwnProperty(b)});if("[object Array]"===Object.prototype.toString.call(_statcounter_pending)&&1<=_statcounter_pending.length&&c(_statcounter_pending[0],"tags")){a=[];for(var l in _statcounter_pending[0].tags)a[a.length]=l,a[a.length]=_statcounter_pending[0].tags[l];if(m(a))for(a=v(a),i=0;i<a.length;i+=2)sc_pageview_tag_string+="&sc_ev_"+encodeURIComponent(a[i])+"="+encodeURIComponent(a[i+1])}})([],256,6,52);
if(sc_script_num)sc_script_num++;else var sc_script_num=1;var sc_tracking_url=sc_base_dir+sc_unique_returning+sc_uuid_q+"&resolution="+sc_width+"&h="+sc_height+"&camefrom="+sc_referer+"&u="+sc_url+"&t="+sc_title+"&java=1&security="+sc_security_code+"&sc_random="+Math.random()+"&sc_snum="+sc_script_num+sc_pageview_tag_string,sc_clstr='<span class="statcounter">';window.sc_counter_width&&window.sc_counter_height&&(sc_counter_size=' width="'+sc_counter_width+'" height="'+sc_counter_height+'"');
window.sc_remove_alt&&(sc_alt_text="");var sc_cltext='" alt="'+sc_alt_text+'" border="0"'+sc_counter_size+">",sc_strout=sc_clstr+sc_link_back_start+'<img src="'+sc_tracking_url+"&p="+sc_prerendering+sc_cltext+sc_link_back_end+"</span>";1==sc_error?document.writeln("Code corrupted. Insert fresh copy."):1!=sc_remove&&sc_write_data();
function sc_write_data(){1==sc_inv||2==sc_prerendering?(window.sc_call?sc_call++:sc_call=1,eval("var sc_img"+sc_call+" = new Image();sc_img"+sc_call+'.src = "'+sc_tracking_url+"&p="+sc_prerendering+'&invisible=1"')):window.sc_text?document.writeln('<script language="JavaScript" src='+sc_tracking_url+"&p="+sc_prerendering+"&text="+sc_text+">\x3c/script>"):document.writeln(sc_strout)}
if(0<sc_cls&&1!=clickstat_done){var sc_exitpage=function(a){ad=document.getElementsByTagName("iframe");if("undefined"!=typeof sc_px)for(a=0;a<ad.length;a++){var b=sc_findx(ad[a]),d=sc_findy(ad[a]),h=parseInt(b,10)+parseInt(ad[a].width,10)+15,c=parseInt(d,10)+parseInt(ad[a].height,10)+10,b=sc_px>b-10&&sc_px<h;sc_py>d-10&&sc_py<c&&b&&(ad[a].src.match(sc_gsyn_pattern)||ad[a].id.match(sc_gsyn_pattern2))&&sc_adsense_click(ad[a])}},sc_findx=function(a){for(var b=0;a;)b+=a.offsetLeft,a=a.offsetParent;return b},
sc_findy=function(a){for(var b=0;a;)b+=a.offsetTop,a=a.offsetParent;return b},sc_getmouse=function(a){"number"==typeof a.pageX?(sc_px=a.pageX,sc_py=a.pageY):"number"==typeof a.clientX&&(sc_px=a.clientX,sc_py=a.clientY,document.body&&(document.body.scrollLeft||document.body.scrollTop)?(sc_px+=document.body.scrollLeft,sc_py+=document.body.scrollTop):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&(sc_px+=document.documentElement.scrollLeft,sc_py+=
document.documentElement.scrollTop))},sc_adsense_init=function(){if(document.all&&"undefined"==typeof window.opera)for(var a=document.getElementsByTagName("iframe"),b=0;b<a.length;b++){if(a[b].src.match(sc_gsyn_pattern)||a[b].id.match(sc_gsyn_pattern2))a[b].onfocus=function(){sc_adsense_click(this)}}else"undefined"!=typeof window.addEventListener&&(window.addEventListener("unload",sc_exitpage,!1),window.addEventListener("mousemove",sc_getmouse,!0))},sc_adsense_click=function(a){var b=a.src.match(sc_gsyn_pattern)?
escape(a.src):escape("Google Adsense "+a.width+"x"+a.height);a=new Image;b=sc_click_dir+"click.gif?sc_project="+clickstat_project+"&security="+clickstat_security+"&c="+b+"&m=2&u="+sc_url+"&t="+sc_title+"&rand="+Math.random();a.src=b;sc_delay()},sc_clickstat_call=function(a,b){if(a){var d=0;lnk.test(a)&&(lnklocal.test(a)?dl.test(a)?d=1:window.sc_exit_link_detect&&(new RegExp(sc_exit_link_detect,"i")).test(a)?d=2:2==sc_cls&&(d=2):d=2);if(0!=d){var h=escape(a);0<h.length&&(d=b+"click.gif?sc_project="+
clickstat_project+"&security="+clickstat_security+"&c="+h+"&m="+d+"&u="+sc_url+"&t="+sc_title+"&rand="+Math.random()+sc_uuid,h=new Image,h.onload=sc_none,h.src=d,sc_delay())}}},sc_delay=function(){for(var a=window.sc_click_stat?window.sc_click_stat:0,b=new Date,a=b.getTime()+a;b.getTime()<a;)b=new Date},sc_none=function(){},clickstat_done=1,clickstat_project=window.sc_project,clickstat_security=window.sc_security_code,dlext="7z|aac|avi|csv|doc|docx|exe|flv|gif|gz|jpe?g|js|mp(3|4|e?g)|mov|pdf|phps|png|ppt|rar|sit|tar|torrent|txt|wma|wmv|xls|xlsx|xml|zip";
"string"==typeof window.sc_download_type&&(dlext=window.sc_download_type);var ltype="https?|ftp|telnet|ssh|ssl|mailto|spotify",second="ac|co|gov|ltd|me|mod|net|nic|nhs|org|plc|police|sch|com",dl=new RegExp("\\.("+dlext+")$","i"),lnk=new RegExp("^("+ltype+"):","i"),domsec=new RegExp("^("+second+")$","i"),host_name=location.host.replace(/^www\./i,""),host_splitted=host_name.split("."),domain=host_splitted.pop(),host_split=host_splitted.pop();domsec.test(host_split)&&(domain=host_split+"."+domain,host_split=
host_splitted.pop());var domain=host_split+"."+domain,lnklocal_mask="^https?://(.*)("+domain+"|webcache.googleusercontent.com)",lnklocal=new RegExp(lnklocal_mask,"i");if(document.getElementsByTagName){var anchors=document.getElementsByTagName("a");for(i=0;i<anchors.length;i++){var anchor=anchors[i];if(anchor.onmousedown){for(var original_click=anchor.onmousedown,s=original_click.toString().split("\n").join(" "),bs=s.indexOf("{"),head=s.substr(0,bs),ps=head.indexOf("("),pe=head.indexOf(")"),params=
head.substring(ps+1,pe),plist=params.split(","),body=s.substr(bs+1,s.length-bs-2),insert="sc_clickstat_call(this,'"+sc_click_dir+"');",final_body=insert+body,ev_head="new Function (",ev_params="",ev_sep="",sc_i=0;sc_i<plist.length;sc_i++)ev_params=ev_sep+"'"+plist[sc_i]+"'",ev_sep=",";","==ev_sep&&(ev_params+=",");var ev_foot="final_body);",ev_final=ev_head+ev_params+ev_foot;anchor.onmousedown=eval(ev_final)}else anchor.onmousedown=new Function("event","sc_clickstat_call(this,'"+sc_click_dir+"');return true;")}}var sc_gsyn_pattern=
"googlesyndication.com|ypn-js.overture.com|ypn-js.ysm.yahoo.com|googleads.g.doubleclick.net",sc_gsyn_pattern2="^aswift_[0-9]+$",sc_px,sc_py;if("undefined"!=typeof window.addEventListener)window.addEventListener("load",sc_adsense_init,!1);else if("undefined"!=typeof document.addEventListener)document.addEventListener("load",sc_adsense_init,!1);else if("undefined"!=typeof window.attachEvent)window.attachEvent("onload",sc_adsense_init);else if("function"==typeof window.onload){var sc_existing=onload;
window.onload=function(){sc_existing();sc_adsense_init()}}else window.onload=sc_adsense_init};